### PR TITLE
First PR- MileStone-1

### PR DESCRIPTION
**Pull request by akshithku**
In this PR I had made the ER Diagram and the Schema for my Hospital Management System. So In this project I had 7 tables like:

1. patient
2. Medical History
3. Doctor
4. Schedule
5. Appointment
6. Attend
7. Diagnose

And there Entities are mentioned in the ER diagram and Schema. 
In Schema I have Also mentioned about the "PRIMARY KEY" and "FOREIGN KEY".

And here is the  LOOM link explanation for this Milestone : [LINK](https://www.loom.com/share/5b6d5ca239f740948427df39591b4b00?sid=0da72cd4-13bd-44e4-b98c-b2f686122728)

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
In ERD, the basic thing is you can not connect attributes with a relation, ( you did it for Attend - Relation)

Medical History should have Patient id foreign key

In doctor, add necessary attributes for qualification, or  doctor type specialist.

You have complicated the appointments with Diagnosis and PatientsAttendAppointment.

You can simply have all the things ( symptopms , diagnosis, prescription, patientId, docId) in Appointment table itself, where the attribute values can be null till updated.

Many tables are simply connected with each other, without proper pointing to foreign keys in schema.

**Comment by akshithku** [comment]
Hey @PRASANNAPATHI 

Thanks for your suggestion, I have made some changes in the Er diagram as you suggested to me. 

So, as you suggested for the Appointment table we can delete the PatientsAttendAppointment if we want, we can add the attributes that are present in the  PatientsAttendAppointment table in the Appointment table, But if we delete it, the no of tables count will be decreased, So do have any suggestion for that.

**Comment by PRASANNAPATHI** [comment]
Update the changes, as discussed.

**Comment by PRASANNAPATHI** [comment]
Yes, Looks fine now, Avoid unnecessary connections for each tables in schema, just have only foreign keys connection.

You can merge it now.

**Pull request merged**
